# roles/sambadc/handlers/main.yml
---

- name: restart sambadc
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - smb
    - nmb

- name: restart firewall
  service:
    name: firewalld
    state: restarted
